# =====================
# BUILD
# =====================
FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build

# =====================
# RUN
# =====================
FROM node:18-alpine AS runner

WORKDIR /app

# Cài nginx
RUN apk add --no-cache nginx

# Cài production dependencies
COPY package*.json ./
RUN npm ci --omit=dev && npm cache clean --force

# Copy build output từ builder
COPY --from=builder /app/dist ./dist

# Copy file env vào container
ARG ENV_FILE=.env.development
COPY ${ENV_FILE} .env

# Copy cấu hình nginx
COPY deploy/.nginx/nginx-dev.conf /etc/nginx/nginx.conf

# Tạo thư mục cần thiết cho nginx
RUN mkdir -p /run/nginx

EXPOSE 80 3000

CMD ["sh", "-c", "nginx && node dist/index.js"]