# =====================
# BUILD
# =====================
FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build

# =====================
# RUN
# =====================
FROM node:18-alpine AS runner

WORKDIR /app

# Cài production dependencies
COPY package*.json ./
RUN npm ci --omit=dev && npm cache clean --force

# Copy build output từ builder
COPY --from=builder /app/dist ./dist

# Copy file env vào container
# ARG ENV_FILE=.env.development
# COPY ${ENV_FILE} .env


EXPOSE 3000

CMD ["node", "dist/index.js"]