worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 1024;
}

http {
    client_max_body_size 100M;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    # Cấu hình gzip, keepalive, logs, v.v.
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://localhost:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
    }
}


# user www-data; #Chạy dưới quyền www-data giúp hạn chế quyền truy cập, giảm thiểu nguy cơ tiềm ẩn
# worker_processes auto;
# pid /run/nginx.pid;
# include /etc/nginx/modules-enabled/*.conf;

# events {
#     worker_connections 1024;
# }

# http {
#     include /etc/nginx/mime.types;
#     default_type application/octet-stream;
    
#     # Bật gzip để giảm dung lượng response
#     gzip on;
#     gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    
#     # Tăng thời gian giữ kết nối
#     keepalive_timeout 65;

#     # Cấu hình logs
#     access_log /var/log/nginx/access.log;
#     error_log /var/log/nginx/error.log;

#     # Cấu hình máy chủ chính
#     server {
#         listen 80;
#         server_name yourdomain.com;

#         # Bảo mật cơ bản
#         add_header X-Frame-Options "SAMEORIGIN";
#         add_header X-XSS-Protection "1; mode=block";
#         add_header X-Content-Type-Options "nosniff";

#         # # Xử lý CORS nếu cần
#         # add_header Access-Control-Allow-Origin *;
#         # add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
#         # add_header Access-Control-Allow-Headers "Authorization, Content-Type";

#         location / {
#             proxy_pass http://localhost:3000;  # Chạy app Node.js trên port 3000
#             proxy_http_version 1.1;
#             proxy_set_header Upgrade $http_upgrade;
#             proxy_set_header Connection 'upgrade';
#             proxy_set_header Host $host;
#             proxy_cache_bypass $http_upgrade;
#         }

#         # Xử lý lỗi 404
#         error_page 404 /404.html;
#         location = /404.html {
#             root /var/www/html;
#         }

#         # Xử lý lỗi 50x
#         error_page 500 502 503 504 /50x.html;
#         location = /50x.html {
#             root /var/www/html;
#         }
#     }
# }
